id: PC0CD31F1
initial_creation_type: input
source_metadata:
  title: Vairotsana Series
  language: en
  description: 'Texts by and about Pagor Vairotsana (fl. 8th C.), the greatest of
    the early Tibetan translators:'
  volume:
    33ebc9b1600644499b852e957cfda569:
      title: Sādhana of the Great Master Vairotsana
      parent: Sādhanas
created_at: '2022-03-01T02:00:38.194176'
last_modified_at: '2022-03-01T02:00:38.194182'
